project:
  type: website

website:
  title: "tb011.github.io"
  navbar:
    left:
      - href: index.qmd #landing page 
        text: Home # button text
      - about.qmd 
      - health_data_analysis.qmd
      - cross-validation.qmd
      - basics-jupyter.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



